cat $CMSSW_BASE/src/PUAnalysis/LT-MC.py > SUB_LT_MC.py
cat submit.py >>SUB_LT_MC.py

#jobID=2019_Jul21_V15JEC
jobID=2019_Jul20-try2-v8JEC



farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                ${jobID}_ggH125  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/VBFHToTauTau_M125_13TeV_powheg_pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15_ext1-v1/MINIAODSIM              ${jobID}_vbfH125  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WplusHToTauTau_M125_13TeV_powheg_pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                              ${jobID}_WHplus  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WminusHToTauTau_M125_13TeV_powheg_pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                              ${jobID}_WHminus  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ZHToTauTau_M125_13TeV_powheg_pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                              ${jobID}_ZH  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                              ${jobID}_ttH  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WW_TuneCP5_13TeV-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                           ${jobID}_WW  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WZ_TuneCP5_13TeV-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v3/MINIAODSIM                               ${jobID}_WZ  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ZZ_TuneCP5_13TeV-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                               ${jobID}_ZZ $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py                    
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                 ${jobID}_DYJ  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                 ${jobID}_DYJ_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                 ${jobID}_DY1  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                 ${jobID}_DY1_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                 ${jobID}_DY2  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                 ${jobID}_DY2_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                 ${jobID}_DY3  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                 ${jobID}_DY3_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                 ${jobID}_DY4  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/EWKWMinus2Jets_WToLNu_M-50_TuneCP5_13TeV-madgraph-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                         ${jobID}_EWKWminus2j  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/EWKWPlus2Jets_WToLNu_M-50_TuneCP5_13TeV-madgraph-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                         ${jobID}_EWKWPlus2j  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/EWKZ2Jets_ZToNuNu_TuneCP5_PSweights_13TeV-madgraph-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                         ${jobID}_EWKZ2j_2l  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/EWKZ2Jets_ZToLL_M-50_TuneCP5_PSweights_13TeV-madgraph-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                         ${jobID}_EWKZ2j_2nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15_ext1-v1/MINIAODSIM               ${jobID}_ST_tw_at  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15_ext1-v1/MINIAODSIM ${jobID}_ST_tW_t  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM         ${jobID}_ST_t_t  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM     ${jobID}_ST_t_at  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                              ${jobID}_TT_2l2nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                              ${jobID}_TT_had  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM                              ${jobID}_TT_sl  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                                ${jobID}_WJ_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                                ${jobID}_WJ_lnu_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                                ${jobID}_W1J_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                                ${jobID}_W2J_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                                ${jobID}_W3J_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM                                ${jobID}_W4J_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py

#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                           ${jobID}_WW_2l2nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                           ${jobID}_WW_4q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                           ${jobID}_WW_lnu2q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                           ${jobID}_WW_lnu2q_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                               ${jobID}_WZ_2l2q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                               ${jobID}_WZ_1l3nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                               ${jobID}_WZ_3lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                               ${jobID}_WZ_lnu2q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                               ${jobID}_ZZ_4l  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                               ${jobID}_ZZ_4l_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                               ${jobID}_ZZ_2l2nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
#farmoutAnalysisJobs    --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=                               ${jobID}_ZZ_2l2q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/farmout/SUB_LT_MC.py
