cat $CMSSW_BASE/src/PUAnalysis/TT-MC.py > SUB_MC.py
cat submit.py >>SUB_MC.py

jobID=2018_Nov30



farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1/MINIAODSIM ${jobID}_tautau_ggH125_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/VBFHToTauTau_M125_13TeV_powheg_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_vbfH125  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WplusHToTauTau_M125_13TeV_powheg_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WHplus  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WminusHToTauTau_M125_13TeV_powheg_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WHminus  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ZHToTauTau_M125_13TeV_powheg_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_ZH  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_ttH  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017RECOSIMstep_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_DYJ  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017RECOSIMstep_12Apr2018_94X_mc2017_realistic_v14_ext1-v1/MINIAODSIM ${jobID}_tautau_DYJ_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_DY1  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_v3_94X_mc2017_realistic_v14_ext1-v2/MINIAODSIM ${jobID}_tautau_DY1_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_DY2  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAOD-PU2017_94X_mc2017_realistic_v11_ext1-v1/MINIAODSIM ${jobID}_tautau_DY2_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_DY3  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1/MINIAODSIM ${jobID}_tautau_DY3_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_v2_94X_mc2017_realistic_v14-v2/MINIAODSIM ${jobID}_tautau_DY4  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/EWKWMinus2Jets_WToLNu_M-50_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_EWKWminus2j  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/EWKWPlus2Jets_WToLNu_M-50_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_EWKWPlus2j  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/EWKZ2Jets_ZToLL_M-50_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_EWKZ2j_2l  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/EWKZ2Jets_ZToNuNu_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_EWKZ2j_2nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM ${jobID}_tautau_ST_tw_at  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM ${jobID}_tautau_ST_tW_t  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ST_t-channel_top_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_ST_t_t  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ST_t-channel_antitop_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM ${jobID}_tautau_ST_t_at  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_TT_2l2nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v2/MINIAODSIM ${jobID}_tautau_TT_had  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_TT_sl  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM ${jobID}_tautau_WJ_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v2/MINIAODSIM ${jobID}_tautau_WJ_lnu_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v3/MINIAODSIM ${jobID}_tautaui_W1J_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v4/MINIAODSIM ${jobID}_tautau_W2J_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_W3J_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_W4J_lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WWTo2L2Nu_NNPDF31_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WW_2l2nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WWTo4Q_NNPDF31_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WW_4q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WWToLNuQQ_NNPDF31_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WW_lnu2q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WWToLNuQQ_NNPDF31_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1/MINIAODSIM ${jobID}_tautau_WW_lnu2q_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WZ_2l2q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8_v2/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WZ_1l3nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WZ_3lnu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM ${jobID}_tautau_WZ_lnu2q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ZZTo4L_13TeV_powheg_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_ZZ_4l  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ZZTo4L_13TeV_powheg_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1/MINIAODSIM ${jobID}_tautau_ZZ_4l_ext  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ZZTo2L2Nu_13TeV_powheg_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_ZZ_2l2nu  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_ZZ_2l2q  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WW_TuneCP5_13TeV-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WW  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/WZ_TuneCP5_13TeV-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_WZ  $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py
farmoutAnalysisJobs  --site-requirements='OpSysAndVer == "SL6"'  --max-usercode-size=150 --vsize-limit=8000 --assume-input-files-exist --input-files-per-job=1 --input-dbs-path=/ZZ_TuneCP5_13TeV-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM ${jobID}_tautau_ZZ $CMSSW_BASE $CMSSW_BASE/src/PUAnalysis/Condor/SUB_MC.py                    
